version: "3"
services:
  app:
    container_name: my-moo-node-server
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DOCKER_DB=mongodb://database:27017/my-moo
  database:
    container_name: database
    image: mongo
    ports:
      - "27018:27017"