name: CD - Server

on:
  push:
    branches: [ develop ]

jobs:
  deployement:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: hello
        run: echo 'hello'
