name: Lighthouse

on:
  pull_request:
    branches: [ develop ]

jobs:
  lighthouse:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Lighthouse Report
        uses: justinribeiro/lighthouse-action@master
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          url: https://arminwindlin.github.io/my-moo/
          wptConnectionSpeed: threegfast