name: My Moo - Testing

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  linting:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencides
        run: npm run ci:client

      - name: run lint
        run: npm run lint:client
