name: My Moo - Testing

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: run lint
          run: npm lint:client
