name: My Moo - Testing

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run lint
          run: npm run lint:client
