name: My Moo - Testing

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  static_tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencides
        run: npm run ci:client

      - name: run lint
        run: npm run lint:client

      - name: dependency check
        uses: AppThreat/dep-scan-action@master
        env:
          VULNDB_HOME: ${{ github.workspace }}/db
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Lighthouse Report
        uses: justinribeiro/lighthouse-action@master
        with:
          url: https://arminwindlin.github.io/my-moo/
          wptConnectionSpeed: threegfast

  sonar:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
