name: Zap Scan

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://arminwindlin.github.io/my-moo/'